# Generated by Django 3.1.6 on 2021-02-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_licenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='version',
        ),
        migrations.AddField(
            model_name='license',
            name='version_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='org_id',
            field=models.IntegerField(default=0),
        ),
    ]
