# Generated by Django 3.1.6 on 2021-02-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_licenses', '0002_auto_20210228_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='creation_date',
            field=models.DateTimeField(null=True, verbose_name='Date created '),
        ),
        migrations.AlterField(
            model_name='license',
            name='creator_address',
            field=models.CharField(max_length=50, null=True, verbose_name='Created by '),
        ),
        migrations.AlterField(
            model_name='license',
            name='org_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='product_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='version_number',
            field=models.CharField(max_length=50, null=True, verbose_name='Version number '),
        ),
    ]
