# Generated by Django 3.1.6 on 2021-03-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_licenses', '0006_license_org_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='creator_phone',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
