# Generated by Django 3.1.6 on 2021-03-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_licenses', '0007_license_creator_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='creator_phone',
            field=models.IntegerField(max_length=99999999999, null=True),
        ),
    ]
