# Generated by Django 3.1.6 on 2021-03-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_licenses', '0008_auto_20210311_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='creator_phone',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
