# Generated by Django 3.1.6 on 2021-03-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_licenses', '0009_auto_20210311_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='IP_Host',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
