# Generated by Django 3.1.6 on 2021-03-13 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_licenses', '0010_auto_20210312_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='entitlement_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
