# Generated by Django 3.1.6 on 2021-03-14 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_licenses', '0011_license_entitlement_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='creator_phone',
        ),
    ]
