# Generated by Django 3.1.6 on 2021-03-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_licenses', '0012_remove_license_creator_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='is_permanent',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
