# Generated by Django 3.1.6 on 2021-03-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_licenses', '0013_auto_20210314_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='is_permanent',
            field=models.BooleanField(default=True),
        ),
    ]
