# Generated by Django 3.1.6 on 2021-03-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_licenses', '0015_auto_20210326_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='creator_phone',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='re_seller',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
