# Generated by Django 3.1.6 on 2021-03-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_licenses', '0016_auto_20210326_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='allowed_ips',
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='creation_date',
            field=models.DateField(null=True, verbose_name='Date created '),
        ),
        migrations.AlterField(
            model_name='license',
            name='expiration_date',
            field=models.DateField(null=True, verbose_name='Expiration date '),
        ),
        migrations.AlterField(
            model_name='license',
            name='product_grade',
            field=models.CharField(default='standard', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='product_stations',
            field=models.IntegerField(default=10000, null=True),
        ),
    ]
