# Generated by Django 3.1.6 on 2021-03-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_licenses', '0017_auto_20210326_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='creation_date',
            field=models.DateTimeField(null=True, verbose_name='Date created '),
        ),
        migrations.AlterField(
            model_name='license',
            name='expiration_date',
            field=models.DateTimeField(null=True, verbose_name='Expiration date '),
        ),
    ]
