# Generated by Django 3.1.6 on 2021-03-31 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_licenses', '0019_auto_20210328_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='license',
            old_name='org_name',
            new_name='max_licenses',
        ),
        migrations.RenameField(
            model_name='license',
            old_name='product_name',
            new_name='organization',
        ),
        migrations.RemoveField(
            model_name='license',
            name='entitlement_id',
        ),
        migrations.RemoveField(
            model_name='license',
            name='org_id',
        ),
        migrations.RemoveField(
            model_name='license',
            name='version_number',
        ),
        migrations.AddField(
            model_name='license',
            name='product',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='total_licenses',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='allowed_ips',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='creation_date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='creator_email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='creator_phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='expiration_date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='is_permanent',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='product_grade',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='product_stations',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
