# Generated by Django 3.1.6 on 2021-04-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_licenses', '0020_auto_20210331_0113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='license',
            old_name='max_licenses',
            new_name='org_name',
        ),
        migrations.RenameField(
            model_name='license',
            old_name='organization',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='license',
            old_name='product',
            new_name='product_version',
        ),
        migrations.RemoveField(
            model_name='license',
            name='total_licenses',
        ),
        migrations.AlterField(
            model_name='license',
            name='allowed_ips',
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='creation_date',
            field=models.DateTimeField(null=True, verbose_name='Date created '),
        ),
        migrations.AlterField(
            model_name='license',
            name='creator_email',
            field=models.CharField(max_length=50, null=True, verbose_name='Created by '),
        ),
        migrations.AlterField(
            model_name='license',
            name='creator_phone',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='expiration_date',
            field=models.DateTimeField(null=True, verbose_name='Expiration date '),
        ),
        migrations.AlterField(
            model_name='license',
            name='is_permanent',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='product_grade',
            field=models.CharField(default='standard', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='product_stations',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
