# Generated by Django 3.1.6 on 2021-04-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_licenses', '0021_auto_20210407_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='max_licenses',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='license',
            name='total_licenses',
            field=models.IntegerField(default=0),
        ),
    ]
