# Generated by Django 3.1.6 on 2021-05-25 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_licenses', '0023_license_is_master'),
    ]

    operations = [
        migrations.DeleteModel(
            name='License',
        ),
    ]
