# Generated by Django 3.1.6 on 2021-03-03 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_organizationName', models.CharField(default='N/A', max_length=200)),
                ('m_IP_Host', models.CharField(default='N/A', max_length=200)),
                ('m_emailAddress', models.EmailField(default='N/A', max_length=200)),
                ('m_phoneNumber', models.CharField(default='N/A', max_length=200)),
                ('m_user', models.CharField(default='N/A', max_length=200)),
                ('m_textFile', models.CharField(default='N/A', max_length=200000)),
                ('m_licenseType', models.CharField(default='N/A', max_length=200)),
                ('m_licenseCreationTime', models.DateTimeField(auto_now_add=True)),
                ('m_notes', models.CharField(default='N/A', max_length=200000)),
                ('m_active', models.CharField(default='yes', max_length=200)),
                ('m_reseller', models.CharField(default='N/A', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ProductLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_licType', models.CharField(default='N/A', max_length=50)),
                ('m_host_IP', models.CharField(default='N/A', max_length=200)),
                ('m_stations', models.IntegerField(default=0)),
                ('m_ips', models.IntegerField(default=0)),
                ('m_task', models.IntegerField(default=0)),
                ('m_log', models.IntegerField(default=0)),
                ('m_node', models.IntegerField(default=0)),
                ('m_sys', models.IntegerField(default=0)),
                ('m_snmp', models.IntegerField(default=0)),
                ('m_startDate', models.IntegerField(default=0)),
                ('m_endDate', models.IntegerField(default=0)),
                ('m_supportID', models.CharField(default='N/A', max_length=200)),
                ('m_expirationDate', models.IntegerField(default=0)),
                ('m_lineNumber', models.IntegerField(default=0)),
                ('m_productName', models.CharField(default='N/A', max_length=200)),
                ('m_productVersion', models.CharField(default='N/A', max_length=200)),
                ('m_grade', models.CharField(default='N/A', max_length=200)),
                ('m_permanent', models.IntegerField(default=0)),
                ('masterLicense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterLicenseGeneratorApp.masterlicense')),
            ],
        ),
    ]
