# Generated by Django 3.1.6 on 2021-02-18 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_contacts', '0004_auto_20210218_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='organization',
        ),
        migrations.AddField(
            model_name='profile',
            name='organization',
            field=models.ManyToManyField(to='manage_contacts.Organization'),
        ),
    ]
