# Generated by Django 3.1.6 on 2021-02-18 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_contacts', '0005_auto_20210218_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entitlement',
            name='organization',
        ),
        migrations.AddField(
            model_name='entitlement',
            name='organization',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='manage_contacts.organization'),
        ),
    ]
