# Generated by Django 3.1.6 on 2021-02-21 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_contacts', '0008_auto_20210218_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='org_id',
        ),
    ]
