# Generated by Django 3.1.6 on 2021-02-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_contacts', '0009_remove_organization_org_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='org_id',
            field=models.CharField(default='0000000', editable=False, max_length=7),
        ),
    ]
