# Generated by Django 3.1.6 on 2021-02-24 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_contacts', '0013_auto_20210224_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
        migrations.RemoveField(
            model_name='entitlement',
            name='organization',
        ),
    ]
