# Generated by Django 3.1.6 on 2021-03-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_contacts', '0017_auto_20210226_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitlement',
            name='product_name',
            field=models.CharField(choices=[('AL', 'AppLoader'), ('SB', 'ScenarioBuilder')], max_length=50, null=True),
        ),
    ]
