# Generated by Django 3.1.6 on 2021-03-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_contacts', '0018_auto_20210311_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitlement',
            name='product_name',
            field=models.CharField(choices=[('AppLoader', 'AppLoader'), ('ScenarioBuilder', 'ScenarioBuilder')], max_length=50, null=True),
        ),
    ]
