# Generated by Django 3.1.6 on 2021-03-13 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_contacts', '0020_auto_20210313_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitlement',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manage_contacts.product'),
        ),
        migrations.AlterField(
            model_name='entitlement',
            name='product_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
