# Generated by Django 3.1.6 on 2021-03-13 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_contacts', '0022_auto_20210313_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entitlement',
            name='product',
        ),
    ]
