# Generated by Django 3.1.6 on 2021-03-13 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_contacts', '0023_remove_entitlement_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entitlement',
            name='product_name',
        ),
        migrations.AddField(
            model_name='entitlement',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manage_contacts.product'),
        ),
    ]
