# Generated by Django 3.1.6 on 2021-03-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_contacts', '0024_auto_20210313_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_version',
            field=models.IntegerField(null=True),
        ),
    ]
