# Generated by Django 3.1.6 on 2021-03-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_contacts', '0025_product_product_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_version',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
