# Generated by Django 3.1.6 on 2021-03-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_contacts', '0026_auto_20210313_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='creation_date',
            field=models.DateTimeField(null=True, verbose_name='Date Created'),
        ),
    ]
