# Generated by Django 3.1.6 on 2021-03-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_contacts', '0028_auto_20210314_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('customer', 'customer'), ('customer', 'partner')], max_length=50, null=True),
        ),
    ]
