# Generated by Django 3.1.6 on 2021-03-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_contacts', '0029_auto_20210315_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitlement',
            name='allowed_ips',
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.AddField(
            model_name='entitlement',
            name='creation_date',
            field=models.DateField(null=True, verbose_name='Date created '),
        ),
        migrations.AddField(
            model_name='entitlement',
            name='creator_email',
            field=models.CharField(max_length=50, null=True, verbose_name='Created by '),
        ),
        migrations.AddField(
            model_name='entitlement',
            name='creator_phone',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='entitlement',
            name='expiration_date',
            field=models.DateField(null=True, verbose_name='Expiration date '),
        ),
        migrations.AddField(
            model_name='entitlement',
            name='host_ip',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entitlement',
            name='is_permanent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='entitlement',
            name='product_grade',
            field=models.CharField(default='standard', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entitlement',
            name='product_stations',
            field=models.IntegerField(default=10000, null=True),
        ),
        migrations.AddField(
            model_name='entitlement',
            name='re_seller',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
