# Generated by Django 3.1.6 on 2021-03-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_contacts', '0030_auto_20210328_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitlement',
            name='is_permanent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entitlement',
            name='product_stations',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
