# Generated by Django 3.1.6 on 2021-03-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_contacts', '0031_auto_20210328_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitlement',
            name='is_permanent',
            field=models.BooleanField(default=None),
        ),
    ]
