# Generated by Django 3.1.6 on 2021-03-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_contacts', '0035_auto_20210328_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitlement',
            name='creation_date',
            field=models.DateTimeField(null=True, verbose_name='Date created '),
        ),
        migrations.AlterField(
            model_name='entitlement',
            name='expiration_date',
            field=models.DateTimeField(null=True, verbose_name='Expiration date '),
        ),
    ]
