# Generated by Django 3.1.6 on 2021-04-02 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_contacts', '0037_auto_20210402_0223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='organization',
        ),
        migrations.AddField(
            model_name='contact',
            name='Organization',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
