# Generated by Django 3.1.6 on 2021-04-02 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_contacts', '0038_auto_20210402_0243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Organization',
        ),
        migrations.AddField(
            model_name='contact',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manage_contacts.organization'),
        ),
    ]
