# Generated by Django 3.1.6 on 2021-04-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_contacts', '0042_auto_20210408_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_grade',
            field=models.CharField(choices=[('standard', 'standard'), ('enterprise', 'enterprise')], default='standard', max_length=50, null=True),
        ),
    ]
