# Generated by Django 3.1.6 on 2021-04-08 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_contacts', '0043_auto_20210408_1926'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entitlement',
        ),
    ]
