# Generated by Django 3.1.6 on 2021-04-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_contacts', '0044_delete_entitlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='page_tab',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
