# Generated by Django 4.1.1 on 2022-10-16 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_contacts', '0046_product_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='organization',
            new_name='product_org',
        ),
    ]
